version: 2
jobs:
  build:
    docker:
      - image: mikoto2000/sphinx:1.7.4
    working_directory: ~/${CIRCLE_PROJECT_REPONAME}/work
    steps:
      - checkout
      - run:
          name: Build html
          command: cd work; make html
      - persist_to_workspace:
          root: work/build/html
          paths:
            - ./*
  deploy:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "af:71:f0:29:0c:e9:cf:44:5b:f3:49:84:52:16:26:b0"
      - attach_workspace:
          at: work/build/html
      - run:
          name: Clone gh-pages
          command: git clone -b gh-pages git@github.com:mikoto2000/${CIRCLE_PROJECT_REPONAME}.git
      - run:
          name: Delete exists file
          command: rm -rf ${CIRCLE_PROJECT_REPONAME}/*
      - run:
          name: Copy build results
          command: cp -rf work/build/html/* ${CIRCLE_PROJECT_REPONAME}
      - run:
          name: Setup git
          command: cd ${CIRCLE_PROJECT_REPONAME};git config --local user.name "${GIT_USER_NAME}"; git config --local user.email "${GIT_EMAIL_ADDRESS}"
      - run:
          name: Git push
          command: cd ${CIRCLE_PROJECT_REPONAME}; git add ./; git commit --allow-empty -m "From `git log --oneline origin/master -n 1`"; git push
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build

